name: hydrodl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - bayesian-optimization=1.1.0
  - cartopy=0.17.0
  - geopandas=0.7.0
  - geoplot=0.4.0
  - geopy=1.21.0
  - pytorch=1.4.0
  - scikit-learn=0.22.2.post1
  - seaborn=0.10.0
  - skorch=0.7.0
  - statsmodels=0.11.1
  - tensorboard=1.15.0
  - torchvision=0.5.0
  - tqdm=4.43.0
  - xlrd=1.2.0
  - shap

